- hosts: all
  gather_facts: yes
  # remote_user: yoozer
  # serial: "50%"  # how many machines to affect at a time
  sudo: yes
  remote_user: root
  tasks:
    - name: Python APT Tools
      when: ansible_os_family == "Debian"
      apt:
        name=python-apt
        update_cache=yes
        state=present

    - name: Repo install
      when: ansible_os_family == "Debian"
      apt_repository:
        repo='deb http://binaries.erlang-solutions.com/{{ansible_distribution|lower}} {{ansible_distribution_release}} contrib'
        update_cache=yes
        state=present

    - name: Erlang (apt)
      when: ansible_os_family == "Debian"
      with_items:
        - elixir
        - erlang-dev
      apt:
        pkg={{item}}
        state=present

    - name: Erlang Solutions Repo Key (CentOS)
      when: ansible_os_family == "RedHat"
      rpm_key:
        key=http://packages.erlang-solutions.com/rpm/erlang_solutions.asc
        state=present

    - name: Erlang Solutions Repo (Debian)
      when: ansible_os_family == "RedHat"
      copy:
        src=erlang-solutions.repo
        dest=/etc/yum.repos.d/erlang-solutions.repo

    - name: Erlang + Headers (CentOS)
      when: ansible_os_family == "RedHat"
      with_items:
        - elixir
        - erlang-dev
      yum:
        name={{item}}
        state=latest
        update_cache=yes

