- hosts: all
  gather_facts: yes
  # remote_user: craun
  # serial: "50%"
  sudo: yes
  tasks:
    - name: Erlang Solutions Repo (apt)
      when: ansible_os_family == "Debian"
      apt_repository:
        repo='deb http://binaries.erlang-solutions.com/{{ansible_distribution}} {{ansible_distribution_release}} contrib'
        state=present

    - name: Erlang Solutions Repo (apt)
      when: ansible_os_family == "Debian"
      apt:
        name=erlang
        update_cache=yes
        state=present

    - name: Erlang Solutions Repo Key (CentOS)
      when: ansible_os_family == "RedHat"
      rpm_key:
        key=http://packages.erlang-solutions.com/rpm/erlang_solutions.asc
        state=present

    - name: Erlang + Headers (Debian)
      when: ansible_os_family == "RedHat"
      copy:
        src=erlang-solutions.repo
        dest=/etc/yum.repos.d/erlang-solutions.repo


    - name: Erlang + Headers (CentOS)
      when: ansible_os_family == "RedHat"
      yum:
        name=erlang
        state=latest
        update_cache=yes
